### ISSUE TITLE
Picker滑到底部然后向上选一格BUG

### ISSUE THREAD

**Issue by xixichensh** [muzin/weex-x-picker#4]
picker滑到底部然后向上选一格或两格，这时候滑轮会选不中

**Comment by leejaygo** [comment]
源码根目录里的index.vue中，每个scroller的后两个text的index计算错误改正就好了。
`<text @disappear="e => disAppearPickItem(e, col_1_ref, col_1_list.length + 3)"
             @appear="e => appearPickItem(e, col_1_ref, col_1_list.length + 3)"
              :ref="col_1_ref + '_text_' + numAdd(col_1_list.length + 3)"
               class="picker-item-text"
             :style="pickerItemTextStyle"></text>
<text @disappear="e => disAppearPickItem(e, col_1_ref, col_1_list.length + 4)"
            @appear="e => appearPickItem(e, col_1_ref, col_1_list.length + 4)"
             :ref="col_1_ref + '_text_' + numAdd(col_1_list.length + 4)"
              class="picker-item-text"
             :style="pickerItemTextStyle"></text>`
改为：
`<text @disappear="e => disAppearPickItem(e, col_1_ref, col_1_list.length-1 + 3)"
             @appear="e => appearPickItem(e, col_1_ref, col_1_list.length-1 + 3)"
              :ref="col_1_ref + '_text_' + numAdd(col_1_list.length-1 + 3)"
               class="picker-item-text"
             :style="pickerItemTextStyle"></text>
<text @disappear="e => disAppearPickItem(e, col_1_ref, col_1_list.length-1 + 4)"
            @appear="e => appearPickItem(e, col_1_ref, col_1_list.length-1 + 4)"
             :ref="col_1_ref + '_text_' + numAdd(col_1_list.length-1 + 4)"
              class="picker-item-text"
             :style="pickerItemTextStyle"></text`

**Comment by muzin** [comment]
已修复这个bug，
并 更新其他功能
1. 新增 通过点击来选中条目
2. 新增 主题色（themeColor）【修改按钮和选中框颜色】，背景色（backgroundColor），条目字体颜色（itemFontColor）
3. 优化 区域选择器

**Comment by xixichensh** [comment]
👍
